name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: |
          pnpm i
          pnpm build 
      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
      - name: Deploy Release
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_ID }}
          secret_key: ${{ secrets.COS_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: dist
          remote_path: ${{ secrets.COS_REMOTE }}
          clean: false